name: CI

"on":
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    name: Build and test the action
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: MoeKernel/checkout@v4.1.6
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+date-%Y-%m-%d-time-%H-%M-%S")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: MoeKernel/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', 'package.json') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', 'package.json') }}-

      - name: Install packages & Build the action
        run: |
           npm ci

      - name: Purge caches
        uses: ./.
        with:
          cache-key: true
          debug: true
          created: true
          accessed: true
          max-age: 259200

      - name: Commit & Push changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          # git rebase master
          git add dist
          git commit -m "action: build the action" || echo ""
          git push
